apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: mysql-flux
spec:
  interval: 5m
  chart:
    spec:
      chart: mysql
      version: "8.6.2"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: mysql-flux
      interval: 1m
      targetNamespace: mysql-deploy
  values:
    image:
      repository: mysql
      tag: 8.0.25
    auth:
      username: fleet
      existingSecret: mysql
    rbac:
      create: true
